stages:
  - test
  - build jar
  - build and push docker image
  - deploy
test_job:
  image: maven:3.6.3-jdk-8
  stage: test
  script:
    - pwd
    - mvn clean
    - mvn compile
    - mvn test
  tags:
    - test
  only:
    - master
build:
  image: maven:3.6.3-jdk-8
  stage: build jar
  script:
    - mvn clean install 
  artifacts:
    paths:
      - target/*.jar
  only:
    - master