stages:
  - test
  - build jar
  - build and push docker image
test_job:
  image: maven:3.6.3-jdk-8
  stage: test
  script:
    - pwd
    - mvn clean
    - mvn compile
    - mvn test

  only:
    - master
