# stages:
#   - test
#   - build jar
#   - build and push docker image

# test_job:
#   image: maven:3.6.3-jdk-8
#   stage: test
#   script:
#     - pwd
#     - mvn clean
#     - mvn compile
    

# build:
#   image: maven:3.6.3-jdk-8
#   stage: build jar
#   script:
#     - mvn install -DskipTests=true


  ######################
stages:
  - build
  - build-docker-image

Build Java Project:
  stage: build
  script:
    mvn package
  artifacts:
    paths:
      - C:\Users\Houssem\Downloads\gitlab-runner

Build Docker Image:
  stage: build-docker-image
  script:
    - docker info
    - docker build -t dihekmissaoui/devops .
