stages:
  - build
  - build-docker-image

Build Java Project:
  stage: build
  script:
    mvn package
  artifacts:
    paths:
      - /Users/Houssem/Downloads/gitlab-runner/

Build Docker Image:
  stage: build-docker-image
  script:
    - docker info
    - docker build -t dihekmissaoui/devops .
  
  
  