stages:
  - test
  - build jar
  - build and push docker image
test_job:
  image: maven:3.6.3-jdk-8
  stage: test
  script:
    - pwd
    - mvn clean
    - mvn compile
    

build:
  image: maven:3.6.3-jdk-8
  stage: build jar
  script:
    - mvn install -DskipTests=true

  only:
    - master

  artifacts:
    paths:
      - target/*.jar

docker build:
  services:
    - maven:3.6.3-jdk-8
  image: maven:3.6.3-jdk-8
  stage: build and push docker image
  script:
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/dihekmissaoui/sbchaletbackend .
    - docker push registry.gitlab.com/dihekmissaoui/sbchaletbackend




    
