stages:
  - test
  - build jar
  - build and push docker image
test_job:
  image: maven:3.6.3-jdk-8
  stage: test
  script:
    - pwd
    - mvn clean
    - mvn compile
    

build:
  image: maven:3.6.3-jdk-8
  stage: build jar
  script:
    - mvn install -DskipTests=true

  only:
    - master

  artifacts:
    paths:
      - target/*.jar
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:test

login_job:
  stage: Login
  tags:
    - docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    

build_job:
  stage: Build
  tags:
    - docker
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    
push_job:
  stage: Push
  tags:
    - docker
  script:
    - docker push $CONTAINER_TEST_IMAGE

logout_job:
  stage: Logout
  tags:
    - docker
  script:
    - docker logout $CI_REGISTRY




    
