stages:
  - test
  - build jar
  - build and push docker image
test_job:
  image: maven:3.6.3-jdk-8
  stage: test
  script:
    - pwd
    - mvn clean
    - mvn compile
    

build:
  image: maven:3.6.3-jdk-8
  stage: build jar
  script:
    - mvn install -DskipTests=true

  only:
    - master

  artifacts:
    paths:
      - target/*.jar

image: docker:19.03.12
services:
  - docker:19.03.12-dind
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest

build_job:
  stage: Build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker logout




    
