variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest
stages:
    - build
    - test


cache:
  paths:
    - .m2/repository
    - target


build_job:
  stage: build
  script: 
    - "mvn compile"


test_job:
  stage: test
  script:
    - "mvn test"


