stages:
  - test
  - build jar
  - build and push docker image
test_job:
  image: maven:3.6.3-jdk-8
  stage: test
  script:
    - pwd
    - mvn clean
    - mvn compile
    

build:
  image: maven:3.6.3-jdk-8
  stage: build jar
  script:
    - mvn install -DskipTests=true

  only:
    - master
image: docker:stable

variables:
    IMAGE_NAME: "maven:3.6.3-jdk-8"
services:
    - docker:19.03.12-dind

build image:
    script:   

      #docker build -t registry.gitlab.com/dihekmissaoui/sbchaletbackend .  
        - docker build -t $CI_REGISTRY/dihekmissaoui/sbchaletbackend/$IMAGE_NAME .
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $CI_REGISTRY/dihekmissaoui/sbchaletbackend/$IMAGE_NAME

        

  
  
  