
stages:
  - build jar
  - build-docker-image
build:
  image: maven:3.6.3-jdk-8
  stage: build jar
  script:
    - mvn clean install -DskipTests=true
Build Docker Image:
  stage: build-docker-image
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - export DOCKER_HOST=tcp://197.2.218.138:2375 && docker build -t $CI_REGISTRY_IMAGE .
    - echo $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
    # - export DOCKER_HOST=tcp://localhost:2375 && docker build -t dihekmissaoui/devops .