stages:
  - test
  - build jar
  - build and push docker image
test_job:
  image: maven:3.6.3-jdk-8
  stage: test
  script:
    - pwd
    - mvn clean
    - mvn compile
    

build:
  image: maven:3.6.3-jdk-8
  stage: build jar
  script:
    - mvn install -DskipTests=true

  only:
    - master

  artifacts:
    paths:
      - target/*.jar

docker build:
  image: docker:latest
  stage: build
  services:
    - docker:build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master




    
